# Generated by Django 5.2 on 2025-06-03 09:05

import giox.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField(max_length=5000)),
                ('image', models.ImageField(upload_to=giox.models.upload_location)),
                ('update', models.DateTimeField(auto_now=True, verbose_name='update')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('liked', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
